# Generated by Django 4.2.28 on 2026-02-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used', models.FloatField(default=0.0)),
                ('distance_miles', models.FloatField(blank=True, null=True)),
                ('duration_hours', models.FloatField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('eld_logs', models.JSONField(blank=True, null=True)),
                ('markers', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
